# Site settings
title: JohnArthurSpalding.com
header-img: img/skellig_michael.jpg
email: your-email@yourdomain.com
copyright_name: John Arthur Spalding
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://johnarthurspalding.com"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  IronSummitMedia
email_username:  your-email@yourdomain.com
navlinks: ["/about/", "/contact/"]

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
