# Site settings
title: JohnArthurSpalding.com
header-img: img/skellig_michael_med.jpg
email: your-email@yourdomain.com
copyright_name: John Arthur Spalding
description: Homepage of author John Arthur Spalding
baseurl: ""
url: "http://johnarthurspalding.com"
twitter_username: JohnASpalding
facebook_username: john.spalding1
email_username:  your-email@yourdomain.com
navlinks: ["/about/", "/contact/"]
defaults:
  -
    scope:
      path: ""
    values:
      layout: post

# Prose.io editor settings
prose:
  siteurl: http://johnarthurspalding.com
  media: img
  ignore: ['.gitignore','CNAME','Gemfile','Gruntfile.js','Makefile','package.json','fonts','js','mail']
  metadata:
    _posts:
      - name: title
        field:
          element: text
          label: Title
      - name: date
        field:
          element: text
          label: Date
          value: CURRENT_DATETIME
      - name: header-img
        field:
          element: text
          label: Header Image
          value: img/skellig_michael_med.jpg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
